/**
 * Typed access to the build-time GitHub data.
 *
 * The raw JSON is generated by scripts/generate-github.ts, so TypeScript infers its shape
 * from whatever happened to be committed — an empty `contributions` object infers as `{}`,
 * which cannot be indexed by a year string. This module states the intended shape once so
 * consumers are not each asserting it.
 */

import raw from './generated/github.json'

export interface ContributionDay {
  readonly date: string
  readonly count: number
  readonly level: number
}

export interface YearContributions {
  readonly total: number
  readonly days: readonly ContributionDay[]
}

export interface GithubData {
  readonly repo: string
  readonly commits: number
  readonly generatedAt: string
  readonly contributions: Readonly<Record<string, YearContributions>>
}

export const github = raw as GithubData

/** Years with committed calendar data, most recent first. */
export const contributionYears: readonly number[] = Object.keys(github.contributions)
  .map(Number)
  .filter((year) => Number.isFinite(year))
  .sort((a, b) => b - a)
